name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: |
          sudo docker build -t bunbb:latest .
      
      - name: Tag Docker Image
        run: |
          sudo docker tag bunbb:latest docker.point.study/bunbb:latest
      
      - name: Login to Docker Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.point.study
      
      - name: Push Docker Image
        run: |
          sudo docker push docker.point.study/bunbb:latest
      
      - name: Update Kubernetes Deployment
        run: |
          kubectl apply -f bunbb-pod.yaml